version: "3"
services:
  db:
    build:
      dockerfile: mysql-Dockerfile
      context: '.'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    container_name: db